### ISSUE TITLE
Criar uma estrutura para Code Trouble

### ISSUE THREAD

**Issue by lucascorreaa** [code-trouble/code-trouble.mobile#1]
### **Contexto**  
O time de Mobile deverá criar a estrutura inicial do repositório utilizando a versão mais atualizada do **React Native** com suporte a **TypeScript**, configurando o projeto para builds futuras em **Android** e **iOS**. O foco deve ser garantir uma base sólida, otimizada para performance e escalabilidade.

### **História do Usuário**  
Como desenvolvedor Mobile,  
Quero criar a estrutura inicial do repositório,  
Para garantir que o projeto tenha uma base sólida, performática e pronta para builds futuras.

---

## **Objetivos**  
1. Inicializar o repositório com a versão atualizada de React Native e TypeScript.  
2. Configurar os arquivos de build para Android e iOS.  
3. Garantir que a estrutura inicial suporte boas práticas de performance e escalabilidade.  

---

## **Critérios de Aceite**

- **Dado** que o repositório foi inicializado,  
  **Quando** analisado,  
  **Então** estará configurado com React Native e TypeScript na versão mais atualizada.  

- **Dado** que a estrutura do projeto foi configurada,  
  **Quando** as builds forem executadas,  
  **Então** será possível compilar para Android e iOS.  

- **Dado** que as boas práticas de performance foram aplicadas,  
  **Quando** o repositório for avaliado,  
  **Então** estará otimizado e escalável.  

---

### Checklist de Tarefas  

1. **Inicializar o projeto**
   - [x] Criar o repositório no GitHub com o nome adequado.  
   - [x] Configurar o projeto com React Native na versão mais recente.  
   - [x] Adicionar suporte ao TypeScript.  

2. **Configurar builds**
   - [x] Configurar arquivos para build em Android.  
   - [ ] Configurar arquivos para build em iOS.  
   - [ ] Testar builds iniciais para ambas as plataformas.  

3. **Organizar a estrutura do projeto**
   - [x] Criar pastas para organização de código (e.g., `src`, `components`, `screens`, `services`).  
   - [ ] Configurar aliases para pastas principais usando `tsconfig.json`.  
   - [ ] Adicionar um README inicial descrevendo a estrutura do projeto.  

4. **Otimizar para performance**
   - [x] Configurar caching de assets (imagens, fontes, etc.).  
   - [x] Habilitar configurações de performance recomendadas no React Native.  
   - [x] Adicionar suporte ao `Hermes` (se aplicável).  

5. **Validar o setup**
   - [ ] Garantir que o projeto compila sem erros em Android e iOS.  
   - [ ] Testar a execução do projeto em emuladores para ambas as plataformas.  
   - [x] Subir a estrutura inicial para o repositório remoto no GitHub.  

---

## **Critérios de Avaliação**

- **Versão Atualizada:** O repositório utiliza a versão mais recente do React Native e TypeScript.  
- **Builds Configurados:** O projeto está preparado para builds em Android e iOS.  
- **Estrutura Clara:** A estrutura do repositório é organizada e escalável para novos desenvolvimentos.  
- **Performance:** Configurações de performance foram aplicadas para otimizar o projeto.  

---

**Comment by lucascorreaa** [comment]
@henriquepablo 

Basicamente, cada PBI, vai ser construído por issue pela sua rastreabilidade dentro do GitHub, e seu vínculo com branch, pull request, para melhorar nosso desempenho como produto. Ela vai ser o mais descritiva possível, para não ficar dúvidas entre o time de desenvolvimento e área de negócio.

Crie uma branch no repositório, faz o que está pedindo na issue, e quando subir abre PR para eu validar, vincule a PR e Branch na issue e arrasta o card para Waiting QA no board, e pode ir buscar outra atividade até eu validar essa.

O que mandou anteriormente sumiu, pode mandar novamente, por gentileza

**Comment by henriquepablo** [comment]
### React Native 
Última versão – 0.76 -> nova arquitetura

**Arquitetura antiga:**
Serialização -> Envio em lote -> Deserialização -> Execução

Na serialização, um código js era empacotado e enviado em lote através da Bridge, depois ocorria a deserialização e por último a chamada do código nativo.
Para a resposta, o processo era o mesmo, só que inverso.

---

**Arquitetura nova:**
Jsi -> TurboModules -> Fabric
O jsi que vai ser responsável por fazer toda a comunicação entre o código js com o nativo, o TurboModules vai ser responsável por trazer um carregamento mais rápido(carregamento lazy dos modules, ou seja, conforme o uso) e Fabric vai renderizar a interface utilizando a JSI para a comunicação.

Dev Tools integrado (facilitando o debug), apertando j do teclado durante a execução do app. Tem mais coisas, mas essas são as principais da nova versão do React Native.

Mas será que as bibliotecas já estão prontas para funcionar com a nova arquitetura?

---

Typescript
pesquisei sobre ele, mas não vi diferenças para comentar.

@lucascorreaa

**Comment by henriquepablo** [comment]
@lucascorreaa 

Como conversei com o senhor no Discord, tive que fazer um downgrade da versão do React Native, pois a última está com problema para iniciar a aplicação. Fiz o downgrade para a versão 0.75.4

**Comment by lucascorreaa** [comment]
@henriquepablo 

Beleza, quando for subir o código abre pr para dev, assim eu consigo ver o código também, antes de subir.

Outro ponto, quando for começar a fazer outra issue, cria a branch aqui para ficar vinculada ou vincula depois:

![image](https://github.com/user-attachments/assets/4f2e1bfc-ea9c-43ba-9dc1-537395868a13)



* Essa versão é a última estável que a comunidade recomenda, deu uma pesquisada?

**Comment by henriquepablo** [comment]
@lucascorreaa 
Sim, dei uma pesquisada nela, ela é a última antes da nova versão. Os últimos projetos que fiz foram nessa versão, e não tive problemas com ela. Testei bibliotecas como styled componentes, React navigation, Integração com Firebase,  e notificações, todos esses recursos funcionaram sem nenhum problema.

**Comment by henriquepablo** [comment]
@lucascorreaa 
Ainda não finalizei essa Issue, só subi o create do projeto. Não tem nada configurado ainda.

Criei uma branch local de conf, depois que eu finalizar as ela, associo a essa Issue e abro pr

**Comment by henriquepablo** [comment]
@lucascorreaa 

Reabri essa issue. Associei ela a pr que acabei de subi. Nela tem algumas configurações, mas maioria delas é relacionada ao **ANDROID**. Testei o build para o Android, tanto o AAB quanto o APK, e os dois tiveram o build corretamente. Também fiz os testes no Emulador e no Device Real.  

**Falta configurar para o IOS**

**Comment by lucascorreaa** [comment]
Perfeito vou testar depois, vou encerrar essa issue

padrão de branch - kebab ou camel

**Comment by henriquepablo** [comment]
Blz. Vou padronizar com o Lapa o padrão camel.
