### ISSUE TITLE
Configuração de Emuladores Android no Android Studio

### ISSUE THREAD

**Issue by lucascorreaa** [code-trouble/code-trouble.mobile#15]
# Configuração de Emuladores Android no Android Studio

## Descrição  
O time mobile da Code Trouble deve configurar os emuladores no Android Studio conforme as especificações abaixo, para alinhamento com as dimensões equivalentes aos dispositivos iPhone SE (3ª geração) e iPhone 16 Plus. Isso garantirá maior consistência nos testes de design responsivo entre Android e iOS.

---

### Especificações do iPhone SE (3ª geração):  
- **Tamanho da tela:** 4.7 polegadas  
- **Resolução:** 750 x 1334 px  
- **Proporção:** 16:9  

### Configuração do Emulador Android:  
1. **Resolução sugerida:** 1280 x 720 px ou 960 x 540 px (formato 16:9).  
2. **Passos para criar o emulador:**  
   - Abra o **AVD Manager** no Android Studio.  
   - Clique em **Create Virtual Device**.  
   - Escolha um dispositivo pequeno (como "Nexus S") ou crie um **Hardware Profile** personalizado com:
     - **Tamanho da tela:** 4.7 polegadas  
     - **Resolução:** 720 x 1280 px  
     - **Proporção:** 16:9  

---

### Especificações do iPhone 16 Plus:  
- **Tamanho da tela:** 6.7 polegadas  
- **Resolução:** 1290 x 2796 px  
- **Proporção:** 19.5:9  

### Configuração do Emulador Android:  
1. **Resolução sugerida:** 1440 x 3120 px (formato 19.5:9).  
2. **Passos para criar o emulador:**  
   - Abra o **AVD Manager** no Android Studio.  
   - Clique em **Create Virtual Device**.  
   - Escolha um dispositivo grande (como "Pixel 6 Pro") ou crie um **Hardware Profile** personalizado com:
     - **Tamanho da tela:** 6.7 polegadas  
     - **Resolução:** 1440 x 3120 px  
     - **Proporção:** 19.5:9  

---

## Critérios de Aceite  
- **Dado** que os emuladores foram configurados,  
  **Quando** o time utilizar os dispositivos virtuais,  
  **Então** o comportamento das telas Android será equivalente aos dispositivos iPhone SE (3ª geração) e iPhone 16 Plus em tamanho e proporção.  

- **Dado** que as configurações foram alinhadas,  
  **Quando** os emuladores forem testados,  
  **Então** será garantida a consistência de design entre as plataformas.  

---

## Tarefas  
- [x] Configurar o emulador Android "Small" conforme especificações acima.  
- [x] Configurar o emulador Android "Large" conforme especificações acima.  
- [x] Validar os emuladores com o time de QA e Design.  

**Responsável:** @henriquepablo @VictorLapaDev 
**Prioridade:** Alta

**Comment by henriquepablo** [comment]
@lucascorreaa 

Já realizei essas configurações do emulador.
