### ISSUE TITLE
Identificar a Melhor Solução de Estilização para Mobile

### ISSUE THREAD

**Issue by lucascorreaa** [code-trouble/code-trouble.mobile#2]
### **Contexto**  
O time de Mobile deverá pesquisar e apresentar a melhor solução para estilização no projeto, considerando **CSS puro**, **pré-processadores** e outras tecnologias do mercado. A escolha deve levar em conta **performance**, **clean code**, **escalabilidade** e a integração com **React Native**. A solução proposta será adotada como padrão para o desenvolvimento do projeto.

### **História do Usuário**  
Como um desenvolvedor Mobile,  
Quero identificar e propor a melhor solução de estilização,  
Para garantir que o código seja performático, escalável e fácil de manter.

---

## **Objetivos**  
1. Pesquisar opções de estilização para React Native, incluindo CSS puro, pré-processadores e bibliotecas modernas.  
2. Comparar as opções com base em performance, clean code e escalabilidade.  
3. Apresentar a solução ideal para o time, com justificativas claras para a escolha.  

---

## **Critérios de Aceite**

- **Dado** que a pesquisa foi concluída,  
  **Quando** for apresentada,  
  **Então** incluirá as vantagens e desvantagens de cada solução avaliada.  

- **Dado** que a solução foi escolhida,  
  **Quando** implementada em um exemplo prático,  
  **Então** demonstrará melhorias em performance, organização e escalabilidade.  

---

### Checklist de Tarefas  

1. **Pesquisa de opções de estilização**
   - [x] Levantar as principais soluções disponíveis para estilização no React Native, como:
     - CSS-in-JS (e.g., `styled-components`, `emotion`, `NativeWind`).
     - Pré-processadores (e.g., SASS, LESS).
     - Soluções nativas de React Native (e.g., `StyleSheet.create`).
   - [x] Analisar documentação e benchmarks de performance.

2. **Análise e Comparação**
   - [x] Comparar as soluções com base nos critérios:
     - **Performance:** Impacto no tempo de renderização e carregamento.
     - **Clean Code:** Organização e legibilidade do código.
     - **Escalabilidade:** Facilidade para expansão do projeto.
   - [x] Listar vantagens e desvantagens de cada solução.

3. **Prototipagem**
   - [x] Implementar uma pequena tela ou componente utilizando a solução proposta.  
   - [x] Testar o desempenho e escalabilidade do exemplo.  

4. **Documentação e Apresentação**
   - [x] Criar uma apresentação resumida com os resultados da pesquisa.  
   - [x] Justificar a solução escolhida com base nos critérios analisados.  

---

## **Dicas e Recomendações**

1. **Para CSS puro ou soluções nativas do React Native:**
   - Use o `StyleSheet.create` para aproveitar a validação e otimização do React Native.
   - Considere a modularização das folhas de estilo para manter o código limpo.

2. **Para CSS-in-JS (e.g., `styled-components` ou `emotion`):**
   - Avalie o impacto no desempenho. Embora sejam convenientes, podem adicionar overhead.
   - Use apenas onde faz sentido, evitando sobrecarga desnecessária.

3. **Para pré-processadores (e.g., SASS, LESS):**
   - Verifique como eles podem ser integrados ao React Native. Geralmente, eles são mais usados em projetos web.

4. **Soluções modernas como Tailwind para React Native (e.g., NativeWind):**
   - Avalie como a abordagem utility-first impacta a escalabilidade.
   - Pode ser interessante para projetos com design padronizado e repetitivo.

5. **Performance e boas práticas:**
   - Prefira classes reutilizáveis ou tokens centralizados (e.g., `theme.js`) para garantir consistência.
   - Minimize re-renders desnecessários devido a mudanças de estilo.

---

## **Critérios de Avaliação**

- **Documentação Completa:** A pesquisa inclui vantagens e desvantagens de cada solução, com comparações claras.  
- **Exemplo Prático:** A solução proposta foi implementada em um protótipo funcional.  
- **Performance:** A solução demonstrou ser leve e rápida durante os testes.  
- **Clean Code:** O código é organizado, modular e fácil de manter.  
- **Escalabilidade:** A solução escolhida suporta o crescimento do projeto sem comprometer a performance.  

---

**Comment by henriquepablo** [comment]
### Estilização para React Native

Algumas possibilidades:

1. React-Native-Sass
2. Styled-Components
3. StyleSheet
4. Tailwind Css

---

- React-Native-Sass

   É uma tecnologia desenvolvida para estilização, mas com alguns recursos adicionados (variáveis, Nested selectors, etc) para melhorar o desenvolvimento.
  
**Vantagens** 

- Utilização de variáveis.
- Organização do código.
- Acelera o desenvolvimento. 


**Desvantagens**

- Transforma o código em um stylesheet, ou seja, processa duas vezes.
- Na hora da compilação, passo adicional para gerar o build.
- Não é nativo, ou seja, é solução de terceiros.
- Pode entrar em conflito com outras formas de estilos.

---
-  Styled-Components

   É uma biblioteca que te permite criar componentes de estilo (css dentro de um arquivo js).
  
**Vantagens** 

- Utilização de variáveis.
- Organização do código.
- Utilização de props nos estilos. (estilos dinâmicos)
- Suporte grande pela comunidade.

**Desvantagens**


- Pode aumentar o tempo de build.
- Pode afetar a Performance  em dispositivos antigos.

--- 

- StyleSheet

  É uma forma nativa de estilização do React Native.

**Vantagens**

- Nativo do React Native.
- Performance alta.
- É uma solução leve.

**Desvantagens**

- Não possui estilos dinâmicos.
- Pode ser dificultoso em projetos grandes.

---

- Tailwind Css
  
   É uma forma de estilização rápida, fazendo ela por meio de classes direto no componente.

**Vantagens**

- Redução de código.
- Desenvolvimento rápido.
- Evita Overhead.

**Desvantagens**

- Não é nativo do React Native (uma adaptação).
- Poluição do jsx com classes longas.
- Tamanho do Bundle, pode afetar a performance.
- Grande dependência externa.

---

@lucascorreaa 

Segue uma análise pequena de algumas soluções que pesquisei junto com o @VictorLapaDev.

Eu considero uma boa solução, utilizar o Styled-Components junto com o StyleSheet. Pois um apresenta uma forma de estilização dinâmica, organização e também com suporte a estilos globais, junto com uma solução nativa.

Vou estar fazendo uma tela pequena com um essas duas soluções.

**Comment by lucascorreaa** [comment]
Também acredito muito no styled-components por conta de conseguir utilizar variáveis, agora o StyleSheet dá muito trabalho quando queremos adicionar variáveis, um grande trabalho no white label no einstein.

Talvez o melhor caminho no momento seja styled, mas o SASS eu não vi, vou dá uma olhada depois

valeu, @henriquepablo @VictorLapaDev, pode entrar em reunião e decidir qual caminho tomar, acredito no styled mesmo para nativo...

**Comment by lucascorreaa** [comment]
Quando decidir, precisamos criar uma estrutura de variáveis de estilos globais com styled-components/native, medias para android/ios, e uma utilização melhor de variáveis de componentes setadas no estilo

ai abre a branch e monta a estrutura no repo @VictorLapaDev @henriquepablo 


OBS:  PODE ALTERAR O NOME PADRÃO DA BRANCH DO ISSUE, QUE FICA MUITO GRANDE E ESTRANHO, AI PODE REDUZIR

**Comment by henriquepablo** [comment]
Vi agora o nome da branch, kkkk

**Comment by henriquepablo** [comment]
Como eu disse sobre o Sass, ele pode entrar em conflito com outras formas de estilos, umas delas é o próprio styled.

**Comment by henriquepablo** [comment]
Conversei com o Lapa, e decidimos seguir com o styled mesmo.

**Comment by lucascorreaa** [comment]
Perfeito, segue com a construção!

Vou trazer uma estrutura...

**Comment by lucascorreaa** [comment]
# Estrutura para uso de `styled-components` com TypeScript

## Estrutura de Pastas

Uma estrutura organizada para o uso de `styled-components`:

```
src/
├── assets/                    # Arquivos estáticos como imagens, fontes, etc.
│   ├── fonts/
│   └── images/
├── components/                # Componentes reutilizáveis
│   └── Button/
│       ├── Button.tsx
│       ├── Button.styles.ts
│       └── index.ts
├── styles/                    # Estilos globais e variáveis
│   ├── breakpoints.ts         # Media queries
│   ├── colors.ts              # Cores do sistema
│   ├── fonts.ts               # Fontes
│   ├── globalStyles.ts        # Estilos globais
│   └── theme.ts               # Tema global
├── types/                     # Tipagens do projeto
│   ├── styled.d.ts            # Declarações globais para styled-components
│   └── index.ts
└── App.tsx
```

## Arquivos e Código

### 1. `theme.ts`
Centralize as variáveis de estilo no tema global.

```typescript
// src/styles/theme.ts
export const theme = {
  colors: {
    primary: '#6200ea',
    secondary: '#03dac6',
    background: '#f4f4f4',
    text: '#333',
  },
  fonts: {
    primary: '"Roboto", sans-serif',
    secondary: '"Open Sans", sans-serif',
  },
  spacing: {
    small: '8px',
    medium: '16px',
    large: '32px',
  },
};
```

### 2. `styled.d.ts`
Use `styled.d.ts` para adicionar suporte de tipagem do tema.

```typescript
// src/types/styled.d.ts
import 'styled-components';
import { theme } from '../styles/theme';

type Theme = typeof theme;

declare module 'styled-components' {
  export interface DefaultTheme extends Theme {}
}
```

### 3. `Button.styles.ts`
Estilos específicos para o componente `Button`.

```typescript
// src/components/Button/Button.styles.ts
import styled from 'styled-components';

interface ButtonProps {
  primary?: boolean;
}

export const Button = styled.button<ButtonProps>`
  background-color: ${({ theme, primary }) => (primary ? theme.colors.primary : theme.colors.secondary)};
  color: ${({ theme }) => theme.colors.text};
  font-family: ${({ theme }) => theme.fonts.primary};
  padding: ${({ theme }) => theme.spacing.medium};
  border: none;
  border-radius: 4px;
  cursor: pointer;

  &:hover {
    opacity: 0.8;
  }
`;
```

### 4. `Button.tsx`
Definição do componente `Button`.

```typescript
// src/components/Button/Button.tsx
import React from 'react';
import { Button as StyledButton } from './Button.styles';

interface ButtonProps {
  onClick: () => void;
  children: React.ReactNode;
  primary?: boolean;
}

const Button: React.FC<ButtonProps> = ({ onClick, children, primary }) => {
  return <StyledButton onClick={onClick} primary={primary}>{children}</StyledButton>;
};

export default Button;
```

### 5. `globalStyles.ts`
Estilos globais para o projeto.

```typescript
// src/styles/globalStyles.ts
import { createGlobalStyle } from 'styled-components';

export const GlobalStyle = createGlobalStyle`
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  body {
    font-family: ${({ theme }) => theme.fonts.primary};
    background-color: ${({ theme }) => theme.colors.background};
    color: ${({ theme }) => theme.colors.text};
  }
`;
```

## Tema no Aplicativo

Configure o tema global no `App.tsx`.

```typescript
// src/App.tsx
import React from 'react';
import { ThemeProvider } from 'styled-components';
import { GlobalStyle } from './styles/globalStyles';
import { theme } from './styles/theme';
import Button from './components/Button/Button';

const App: React.FC = () => (
  <ThemeProvider theme={theme}>
    <GlobalStyle />
    <Button onClick={() => alert('Button clicked')} primary>
      Click me
    </Button>
  </ThemeProvider>
);

export default App;
```

## Considerações sobre Performance e Clean Code
- **Organização**: Estrutura limpa e separação clara entre componentes e estilos.
- **Reutilização**: Uso de variáveis de tema para consistência.
- **TypeScript**: Tipagem robusta para evitar erros.
- **Performance**: Uso eficiente de estilos dinâmicos e variáveis globais.

Essa estrutura promove um desenvolvimento eficiente, limpo e de alta performance.


Pensei em algo assim, para inicio @VictorLapaDev @henriquepablo

**Comment by henriquepablo** [comment]
Blz, vamos implementar essa estrutura.
