### ISSUE TITLE
Identificar a Melhor Solução de Formatação e Lint

### ISSUE THREAD

**Issue by lucascorreaa** [code-trouble/code-trouble.mobile#3]
### **Contexto**  
O time de Mobile deverá pesquisar e apresentar a melhor solução para formatação e linting no projeto, avaliando ferramentas como **Biome**, **ESLint** e **Prettier**. A solução deve ser pensada para garantir **clean code**, **padronização**, **performance** e facilidade de integração ao fluxo de trabalho da equipe.

### **História do Usuário**  
Como um desenvolvedor Mobile,  
Quero identificar e propor a melhor solução de formatação e lint,  
Para garantir que o código seja padronizado, limpo e fácil de manter.

---

## **Objetivos**  
1. Pesquisar ferramentas de linting e formatação adequadas para React Native.  
2. Comparar as ferramentas com base em performance, customização e impacto no fluxo de trabalho.  
3. Apresentar a solução ideal para o time, com justificativas claras para a escolha.  

---

## **Critérios de Aceite**

- **Dado** que a pesquisa foi concluída,  
  **Quando** for apresentada,  
  **Então** incluirá as vantagens e desvantagens de cada ferramenta avaliada.  

- **Dado** que a solução foi escolhida,  
  **Quando** implementada no repositório,  
  **Então** permitirá que o código siga os padrões definidos com facilidade.  

---

### Checklist de Tarefas  

1. **Pesquisa de ferramentas**
   - [x] Levantar as principais ferramentas de formatação e linting, como:
     - **Biome** (lint + format em uma única ferramenta).
     - **ESLint** (customizável e amplamente utilizado).
     - **Prettier** (formatador automático de código).
   - [x] Analisar documentação, benchmarks de performance e casos de uso.  

2. **Análise e Comparação**
   - [x] Comparar as ferramentas com base nos critérios:
     - **Performance:** Impacto no tempo de execução em projetos React Native.  
     - **Customização:** Capacidade de configurar regras específicas.  
     - **Fluxo de Trabalho:** Integração com editores (e.g., VSCode) e pipelines CI/CD.  
   - [ ] Listar vantagens e desvantagens de cada solução.  

3. **Prototipagem**
   - [x] Configurar um exemplo básico utilizando as ferramentas avaliadas:
     - Configurar **Biome** para linting e formatação.
     - Configurar **ESLint** com regras específicas para React Native.
     - Configurar **Prettier** integrado ao ESLint, se aplicável.
   - [x] Testar o impacto no código base e na experiência do desenvolvedor.  

4. **Documentação e Apresentação**
   - [x] Criar uma apresentação resumida com os resultados da pesquisa.  
   - [ ] Justificar a solução escolhida com base nos critérios analisados.  

---

## **Dicas e Recomendações**

1. **Biome (lint + format):**
   - Ideal para simplificar o setup, já que combina lint e formatação em uma única ferramenta.
   - Verifique o suporte e performance para React Native.

2. **ESLint:**
   - Amplamente usado e altamente configurável.
   - Adicione plugins específicos para React Native, como `eslint-plugin-react-native`.

3. **Prettier:**
   - Excelente para formatação automática, garantindo consistência em espaços, quebras de linha, etc.
   - Integre com ESLint para evitar conflitos de regras.

4. **Performance e integração:**
   - Certifique-se de que a ferramenta escolhida funcione bem em ambientes locais e CI/CD.
   - Considere adicionar hooks no `pre-commit` usando ferramentas como **Husky** para validar lint e formatação antes de cada commit.

---

## **Critérios de Avaliação**

- **Documentação Completa:** A pesquisa inclui vantagens e desvantagens de cada ferramenta, com comparações claras.  
- **Exemplo Prático:** A solução proposta foi configurada e testada no repositório.  
- **Fluxo de Trabalho Otimizado:** A solução escolhida não impacta negativamente a produtividade dos desenvolvedores.  
- **Padronização e Clean Code:** A configuração garante que todo o código siga os mesmos padrões.  
- **Performance:** A solução é rápida e eficiente em projetos React Native.  

---

**Comment by henriquepablo** [comment]
Já começamos a pesquisar sobre a melhor forma de formatação. Quando finalizarmos, mandaremos aqui a pesquisa.

**Comment by lucascorreaa** [comment]
Atualizem o board lá, o kanban, lembra?

Vai chegar um momento que precisa ser autogerenciável e o pessoal de agilidade precisa ver o que estão fazendo pelo board.

**Comment by henriquepablo** [comment]
Está atualizado, coloquei em progresso assim que mandei a mensagem.

**Comment by henriquepablo** [comment]
### Formatação para React Native

Algumas possibilidades:

1. Biome
2. Eslint
3. Prettier

---

- Biome

   formatador de código, com suporte a ts tsx, etc. O diferencial dele é que tem duas ferramentas em uma, ou seja, ele já formatar e analisa o código
  
**Vantagens** 

- Rápido.
- Otimizado.
- Escalável. 


**Desvantagens**

- Compatibilidade ilimitada, ou seja, pode ser que ocorra problemas com bibliotecas.
- Pode ocorrer overhead.

---
-  Eslit

   É uma ferramenta que analisa o código e procura por erros.
  
**Vantagens** 

- Padronização do código.
- Facilidade de integração com ferramentas de desenvolvimento.
- Melhor desempenho em projetos grandes.

**Desvantagens**


- Sinalizar problema onde não há.
- Deixar de sinalizar problemas.
- Pode aumentar o tempo de build.

--- 

- Prettier

  Ferramenta para formatação de código.

**Vantagens**

- Formatação Uniforme.
- Padronização automática.
- Facilidade de integração.

**Desvantagens**

- Não possui personalização avançada.
- Conflito com outras ferramentas de litting.


@lucascorreaa

**Comment by henriquepablo** [comment]
Estamos pensando em utilizar o Biome, pois ele é uma ferramenta que possui duas funcionalidades(formatação e lint) em um único lugar, evitando a necessidade de configuração de mais de uma ferramenta.

**Comment by lucascorreaa** [comment]
@henriquepablo 

vamos tentar o Biome, pode configurar

Quero apenas aspas simples, sem ponto e virgula, por enquanto adicionamos outras regras de formtação depois

**Comment by henriquepablo** [comment]
@lucascorreaa 

Falei com o Lapa, e é melhor definir os nomes das branch com o padrão kebab.

**Comment by lucascorreaa** [comment]
Fica melhor mesmo para leitura...
