### ISSUE TITLE
Refatorar telas OnBoarding

### ISSUE THREAD

**Issue by lucascorreaa** [code-trouble/code-trouble.mobile#33]
Refatorar telas do OnBoarding, utilizar sempre o breakpoints, Iphone SE e Iphone 16 Plus, como não tem IOS, pode usar as dimensões e criar android que correspondem a eles.

Renomear a screen para OnBoarding:

<img width="349" alt="image" src="https://github.com/user-attachments/assets/686a111f-f08a-4e57-bbe2-0e2096e30927" />

- Ponto de Atenção é abrir dispositivos maiores e medianos, para que sempre o media pegue os demais dispositivos.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b93ab513-a4c6-4c14-8e04-2f23c064f3f2" />

@henriquepablo @VictorLapaDev

**Comment by henriquepablo** [comment]
@lucascorreaa qual é a dimensão desse emulador? Porquei testei nos emuladores e no dispositivo real e em todos estava normal. Até aumentamos o breakpoint para 640 para dispositivo médio.

**Comment by lucascorreaa** [comment]
O iPhone SE (3ª geração) possui as seguintes dimensões:

Altura: 138,4 mm
Largura: 67,3 mm

**Comment by henriquepablo** [comment]
Interessante

**Comment by lucascorreaa** [comment]
cara, estou olhando aqui acho que é a função breakpoints(), to dando uma olhada aqui

**Comment by lucascorreaa** [comment]
código está bom em...

da uma olhada no zustand ou redux, para fazer esse controle de estado

[zustand](https://zustand-demo.pmnd.rs/)
[redux](https://redux.js.org/)

**Comment by henriquepablo** [comment]
De fato, preciso refazer esse gerenciamento, tá ruim

**Comment by lucascorreaa** [comment]
estava olhando essa lib aqui:

https://www.npmjs.com/package/react-native-responsive-screen

mas vi que o codigo é simples, ai roubei pra nós, estou testando

https://github.com/marudy/react-native-responsive-screen/blob/master/index.js

**Comment by henriquepablo** [comment]
De fato, é bem tranquila, parece uma boa utilizar

**Comment by lucascorreaa** [comment]
deu ruim, ainda to pensando na solução

**Comment by henriquepablo** [comment]
O que pensei é utilizar a função breakpoint com redux

**Comment by lucascorreaa** [comment]
subi pra 670 e roda no iphone SE

if (breakpoints() > 670) setLarge(true)

pesquisa sobre validação de breakpoint, em tempo real e controle, ai verifica zustand ou redux

**Comment by henriquepablo** [comment]
Blz

**Comment by henriquepablo** [comment]
Verifiquei o zustand e parece ser mais simples do que Redux, não exige tanta configuração e não fica confuso

**Comment by lucascorreaa** [comment]
boa

faz com ele, e coloca o media no app.tsx, que é primeira montagem, e seta globalmente

**Comment by lucascorreaa** [comment]
Talvez melhore o desempenho do breakpoint

Haaa outro ponto, quando criar um helper chama com use no começo

useBreakpoint

**Comment by henriquepablo** [comment]
Blz, se der tempo hoje, já faço
