### ISSUE TITLE
Criar fluxo de telas com dados mockados

### ISSUE THREAD

**Issue by lucascorreaa** [code-trouble/code-trouble.mobile#36]
### Contexto  
O time de mobile precisa implementar um fluxo de telas básico para o aplicativo, utilizando dados mockados. O objetivo é construir a navegação inicial do app, começando pelo onboarding, seguido por login, registro e telas subsequentes. Esse fluxo será usado como base para testes e iteração.

### História do Usuário  
**Como** um usuário,  
**Quero** navegar pelas telas do aplicativo em um fluxo lógico,  
**Para que** eu tenha uma experiência consistente desde a abertura inicial do app.

### Objetivos  
1. Criar um fluxo de navegação entre as telas principais do app.  
2. Implementar telas com dados mockados para simular a experiência do usuário.  
3. Garantir que o fluxo funcione corretamente em diferentes cenários (primeiro uso, login já realizado, etc.).

---

## Critérios de Aceite  

- **Dado** que o usuário abre o app pela primeira vez,  
  **Quando** a navegação for iniciada,  
  **Então** ele deve visualizar as telas de onboarding.

- **Dado** que o usuário finaliza o onboarding,  
  **Quando** selecionar prosseguir,  
  **Então** ele será redirecionado para a tela de login.

- **Dado** que o usuário está na tela de login,  
  **Quando** clicar para se registrar,  
  **Então** ele será levado à tela de registro.

- **Dado** que o usuário já está autenticado,  
  **Quando** abrir o app,  
  **Então** ele deve ser redirecionado automaticamente para a tela principal (home).

---

### Checklist de Tarefas  
1. **Configurar navegação**  
   - [x] Adicionar um sistema de navegação no app (e.g., React Navigation).  
   - [x] Criar as rotas e configurar os fluxos de navegação.

2. **Implementar as telas com mock de dados**  
   - [x] Tela de Onboarding (informações sobre o app, botão de prosseguir).  
   - [x] Tela de Login (email/senha e botão de registrar).  
   - [x] Tela de Registro (formulário básico e botão para criar conta).  
   - [x] Tela Principal (após o login).

3. **Simular diferentes fluxos de usuário**  
   - [x] Primeiro acesso (exibe onboarding e redireciona para login).  
   - [x] Usuário autenticado (pula o onboarding/login e vai direto para a home).

4. **Validar transições e estados**  
   - [x] Garantir transições suaves entre as telas.  
   - [x] Testar estados como: primeira vez no app, login concluído, etc.

---

## Observações  
- Utilize mock de dados para formulários de login e registro.  
- Não é necessário conectar com APIs nesta etapa.  
- Certifique-se de que a navegação é intuitiva e funcional em dispositivos diferentes.

**Comment by henriquepablo** [comment]
Eu tinha pensando nisso, mas pensei que iria ser feito já com back end integrado

**Comment by henriquepablo** [comment]
Para este cenário, pensei em fazer com async storage a emulação do fluxo funcionando. Ou seja, a cada etapa avançada, adiciono a informação no async storage e depois só faço o consumo.

**Comment by lucascorreaa** [comment]
zustand e redux, não seria melhor?

**Comment by lucascorreaa** [comment]
> Eu tinha pensando nisso, mas pensei que iria ser feito já com back end integrado

ta achando que estou de toca, backend tá mal das pernas

**Comment by henriquepablo** [comment]
> zustand e redux, não seria melhor?

Então, seria sim, mas para o fluxo que o senhor quer, só zustand e redux não seria o suficiente. Para o fluxo de estar logado e pular onboarding e tela de login, é necessário persistência de dados.

**Comment by lucascorreaa** [comment]
verdade...

faz pesquisa de mercado sobre

**Comment by henriquepablo** [comment]
Tem algumas opções, como: offline first, sql lite, mmkv (é um banco e alternativa ao async storage)...

**Comment by henriquepablo** [comment]
Dá para simular com mmkv e usar em conjunto com async storage, como é para representar o fluxo. Quando fizer o login, salvamos o email no async storage, e se houver um email salvo, a navegação vai direto para a tela home.

**Comment by henriquepablo** [comment]
@lucascorreaa , ainda não foi finalizado, falta adicionar mais uma lógica
