### ISSUE TITLE
Identificar a Melhor Solução de Testes

### ISSUE THREAD

**Issue by lucascorreaa** [code-trouble/code-trouble.mobile#4]
Criar solução, exemplo:

* Vitest
* Jest

**Comment by VictorLapaDev** [comment]
### Formatação para React Native
Algumas possibilidades:
1. Jest
2. Vitest
---

- Jest

Ferramenta de teste feita para ser utilizada em aplicações com react e react-native.

#### Vantagens

- Amplamente utilizado.
- Fácil configuração.
- Tem suporte para react-native.

#### Desvantagens

- Uso intensivo de memória em projetos grandes.
- Atraso no suporte de novos recursos.
---

- Vitest

Framework de teste mais recente otimizado para typescript e vite.

#### Vantagens

- Extremamente rápido.
- Suporte completo para typescript.
- Execução paralela.

#### Desvantagens

- Foi criada para projetos com vite, não foi feito para react-native.
- Ferramenta mais recente
---


@lucascorreaa

**Comment by lucascorreaa** [comment]
Segue com jest

**Comment by henriquepablo** [comment]
@VictorLapaDev 
Nas últimas versões do react native, aparentemente o jest já vem configurado

**Comment by lucascorreaa** [comment]
Então testa a funcionalidade e pode encerrar a issue, demonstrando que está configurado...

**Comment by henriquepablo** [comment]
O que exatamente deve ser testado?

**Comment by henriquepablo** [comment]
Não sei se era isso. Mas rodei o teste, e o jest respondeu como o esperado.

![{B94FD230-B52B-4A19-8D14-E4B5C08B776D}](https://github.com/user-attachments/assets/5800be79-f960-4164-970e-fbe5241a2125)

![{34112FEB-E1EE-42B3-A987-B2A4DD322956}](https://github.com/user-attachments/assets/777148df-b1ad-4fa3-b161-ddda47b0f099)

![{CEABEF35-0324-459F-ABA5-C5ACD5E7898C}](https://github.com/user-attachments/assets/a4480869-b5fe-4077-8a3e-f599d1f42c89)
